language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install flake8
 
script: 
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
